In [6]:


import pandas as pd

In [23]:
price_1 = pd.read_csv("ROUND1_data/prices_round_1_day_-2.csv", sep = ';', header = 0)
price_2 = pd.read_csv("ROUND1_data/prices_round_1_day_-1.csv", sep = ';', header = 0)
price_3 = pd.read_csv("ROUND1_data/prices_round_1_day_0.csv", sep = ';', header = 0)

In [29]:
ash_1 = price_1[price_1["product"] == "ASH_COATED_OSMIUM"]
pepper_1 = price_2[price_2["product"] == "INTARIAN_PEPPER_ROOT"]

ash_2 = price_2[price_2["product"] == "ASH_COATED_OSMIUM"]
pepper_2 = price_2[price_2["product"] == "INTARIAN_PEPPER_ROOT"]

ash_3 = price_3[price_3["product"] == "ASH_COATED_OSMIUM"]
pepper_3 = price_3[price_3["product"] == "INTARIAN_PEPPER_ROOT"]

In [30]:
ash_1

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
1,-2,0,ASH_COATED_OSMIUM,NaN,NaN,NaN,NaN,NaN,NaN,10010.0,25.0,NaN,NaN,NaN,NaN,10010.0,0.0
3,-2,100,ASH_COATED_OSMIUM,9992.0,15.0,NaN,NaN,NaN,NaN,10008.0,15.0,10011.0,20.0,NaN,NaN,10000.0,0.0
5,-2,200,ASH_COATED_OSMIUM,9992.0,15.0,9989.0,30.0,NaN,NaN,10008.0,15.0,10010.0,30.0,NaN,NaN,10000.0,0.0
6,-2,300,ASH_COATED_OSMIUM,9992.0,13.0,9989.0,26.0,NaN,NaN,10008.0,13.0,10010.0,26.0,NaN,NaN,10000.0,0.0
8,-2,400,ASH_COATED_OSMIUM,9992.0,15.0,NaN,NaN,NaN,NaN,10008.0,15.0,10010.0,20.0,NaN,NaN,10000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19990,-2,999500,ASH_COATED_OSMIUM,9984.0,13.0,9982.0,24.0,NaN,NaN,10000.0,13.0,10003.0,24.0,NaN,NaN,9992.0,0.0
19992,-2,999600,ASH_COATED_OSMIUM,9984.0,15.0,9982.0,30.0,NaN,NaN,10000.0,15.0,10003.0,30.0,NaN,NaN,9992.0,0.0
19995,-2,999700,ASH_COATED_OSMIUM,9984.0,10.0,9982.0,22.0,NaN,NaN,10000.0,10.0,10003.0,22.0,NaN,NaN,9992.0,0.0
19997,-2,999800,ASH_COATED_OSMIUM,9984.0,14.0,9982.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9984.0,0.0
19999,-2,999900,ASH_COATED_OSMIUM,9984.0,13.0,NaN,NaN,NaN,NaN,10003.0,30.0,NaN,NaN,NaN,NaN,9993.5,0.0

In [31]:
ash_2

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
1,-1,0,ASH_COATED_OSMIUM,NaN,NaN,NaN,NaN,NaN,NaN,10003.0,29.0,NaN,NaN,NaN,NaN,10003.0,0.0
2,-1,100,ASH_COATED_OSMIUM,9984.0,11.0,NaN,NaN,NaN,NaN,10000.0,11.0,10003.0,22.0,NaN,NaN,9992.0,0.0
4,-1,200,ASH_COATED_OSMIUM,9985.0,15.0,9982.0,20.0,NaN,NaN,10001.0,15.0,10003.0,20.0,NaN,NaN,9993.0,0.0
7,-1,300,ASH_COATED_OSMIUM,9985.0,11.0,9982.0,29.0,NaN,NaN,10001.0,11.0,10003.0,29.0,NaN,NaN,9993.0,0.0
9,-1,400,ASH_COATED_OSMIUM,9985.0,12.0,NaN,NaN,NaN,NaN,10001.0,12.0,10004.0,25.0,NaN,NaN,9993.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19990,-1,999500,ASH_COATED_OSMIUM,9992.0,29.0,NaN,NaN,NaN,NaN,10010.0,14.0,10013.0,29.0,NaN,NaN,10001.0,0.0
19993,-1,999600,ASH_COATED_OSMIUM,9994.0,14.0,NaN,NaN,NaN,NaN,10010.0,14.0,NaN,NaN,NaN,NaN,10002.0,0.0
19994,-1,999700,ASH_COATED_OSMIUM,9994.0,12.0,NaN,NaN,NaN,NaN,10013.0,26.0,NaN,NaN,NaN,NaN,10003.5,0.0
19997,-1,999800,ASH_COATED_OSMIUM,9994.0,13.0,9992.0,20.0,NaN,NaN,10010.0,13.0,10013.0,20.0,NaN,NaN,10002.0,0.0
19998,-1,999900,ASH_COATED_OSMIUM,9994.0,10.0,NaN,NaN,NaN,NaN,10010.0,10.0,10013.0,29.0,NaN,NaN,10002.0,0.0

In [32]:
pepper_1

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-1,0,INTARIAN_PEPPER_ROOT,10991.0,15.0,NaN,NaN,NaN,NaN,11006.0,10.0,11009.0,15.0,NaN,NaN,10998.5,0.0
3,-1,100,INTARIAN_PEPPER_ROOT,10994.0,9.0,10991.0,21.0,NaN,NaN,11006.0,9.0,11009.0,21.0,NaN,NaN,11000.0,0.0
5,-1,200,INTARIAN_PEPPER_ROOT,10994.0,10.0,NaN,NaN,NaN,NaN,11009.0,20.0,NaN,NaN,NaN,NaN,11001.5,0.0
6,-1,300,INTARIAN_PEPPER_ROOT,NaN,NaN,NaN,NaN,NaN,NaN,11006.0,9.0,11009.0,21.0,NaN,NaN,11006.0,0.0
8,-1,400,INTARIAN_PEPPER_ROOT,10992.0,20.0,NaN,NaN,NaN,NaN,11006.0,11.0,11009.0,20.0,NaN,NaN,10999.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19991,-1,999500,INTARIAN_PEPPER_ROOT,11993.0,8.0,NaN,NaN,NaN,NaN,12006.0,8.0,12009.0,23.0,NaN,NaN,11999.5,0.0
19992,-1,999600,INTARIAN_PEPPER_ROOT,NaN,NaN,NaN,NaN,NaN,NaN,12006.0,8.0,12009.0,18.0,NaN,NaN,12006.0,0.0
19995,-1,999700,INTARIAN_PEPPER_ROOT,11993.0,10.0,NaN,NaN,NaN,NaN,12006.0,10.0,NaN,NaN,NaN,NaN,11999.5,0.0
19996,-1,999800,INTARIAN_PEPPER_ROOT,11993.0,12.0,11990.0,18.0,NaN,NaN,12009.0,18.0,NaN,NaN,NaN,NaN,12001.0,0.0
19999,-1,999900,INTARIAN_PEPPER_ROOT,11990.0,25.0,NaN,NaN,NaN,NaN,12006.0,10.0,12009.0,25.0,NaN,NaN,11998.0,0.0

In [33]:
pepper_2

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-1,0,INTARIAN_PEPPER_ROOT,10991.0,15.0,NaN,NaN,NaN,NaN,11006.0,10.0,11009.0,15.0,NaN,NaN,10998.5,0.0
3,-1,100,INTARIAN_PEPPER_ROOT,10994.0,9.0,10991.0,21.0,NaN,NaN,11006.0,9.0,11009.0,21.0,NaN,NaN,11000.0,0.0
5,-1,200,INTARIAN_PEPPER_ROOT,10994.0,10.0,NaN,NaN,NaN,NaN,11009.0,20.0,NaN,NaN,NaN,NaN,11001.5,0.0
6,-1,300,INTARIAN_PEPPER_ROOT,NaN,NaN,NaN,NaN,NaN,NaN,11006.0,9.0,11009.0,21.0,NaN,NaN,11006.0,0.0
8,-1,400,INTARIAN_PEPPER_ROOT,10992.0,20.0,NaN,NaN,NaN,NaN,11006.0,11.0,11009.0,20.0,NaN,NaN,10999.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19991,-1,999500,INTARIAN_PEPPER_ROOT,11993.0,8.0,NaN,NaN,NaN,NaN,12006.0,8.0,12009.0,23.0,NaN,NaN,11999.5,0.0
19992,-1,999600,INTARIAN_PEPPER_ROOT,NaN,NaN,NaN,NaN,NaN,NaN,12006.0,8.0,12009.0,18.0,NaN,NaN,12006.0,0.0
19995,-1,999700,INTARIAN_PEPPER_ROOT,11993.0,10.0,NaN,NaN,NaN,NaN,12006.0,10.0,NaN,NaN,NaN,NaN,11999.5,0.0
19996,-1,999800,INTARIAN_PEPPER_ROOT,11993.0,12.0,11990.0,18.0,NaN,NaN,12009.0,18.0,NaN,NaN,NaN,NaN,12001.0,0.0
19999,-1,999900,INTARIAN_PEPPER_ROOT,11990.0,25.0,NaN,NaN,NaN,NaN,12006.0,10.0,12009.0,25.0,NaN,NaN,11998.0,0.0